//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gMapMaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gMapMaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application failed to generate merged image and/or map..
        /// </summary>
        internal static string ApplicationErrorText {
            get {
                return ResourceManager.GetString("ApplicationErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Error !.
        /// </summary>
        internal static string ApplicationErrorTitle {
            get {
                return ResourceManager.GetString("ApplicationErrorTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap browser64 {
            get {
                object obj = ResourceManager.GetObject("browser64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad .map file ({0})..
        /// </summary>
        internal static string ExceptionBadMapFile {
            get {
                return ResourceManager.GetString("ExceptionBadMapFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot build blank tile image..
        /// </summary>
        internal static string ExceptionCannotBuildBlankImage {
            get {
                return ResourceManager.GetString("ExceptionCannotBuildBlankImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert image to 24bpp..
        /// </summary>
        internal static string ExceptionCannotConvert24bpp {
            get {
                return ResourceManager.GetString("ExceptionCannotConvert24bpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert image to grayscale..
        /// </summary>
        internal static string ExceptionCannotConvertGrayscale {
            get {
                return ResourceManager.GetString("ExceptionCannotConvertGrayscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save file {0}..
        /// </summary>
        internal static string ExceptionCannotSaveFile {
            get {
                return ResourceManager.GetString("ExceptionCannotSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while converting image from 24bpp to 8bpp. Image to bigger than available memory ?.
        /// </summary>
        internal static string ExceptionConversion24bpp8bpp {
            get {
                return ResourceManager.GetString("ExceptionConversion24bpp8bpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while downloading image (Your IP may be blacklisted by Google)..
        /// </summary>
        internal static string ExceptionDownloadingImage {
            get {
                return ResourceManager.GetString("ExceptionDownloadingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while initializing big image grayscale palette..
        /// </summary>
        internal static string ExceptionGrayscalePalette {
            get {
                return ResourceManager.GetString("ExceptionGrayscalePalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config file parameter MGMapsHashSize must be &gt; 0.
        /// </summary>
        internal static string ExceptionHashSizeNegative {
            get {
                return ResourceManager.GetString("ExceptionHashSizeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while allocating memory. Image too big..
        /// </summary>
        internal static string ExceptionImageMemoryAllocation {
            get {
                return ResourceManager.GetString("ExceptionImageMemoryAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect longitude/latitude. May be you have inverted top-left and bottom-right coordinates ?.
        /// </summary>
        internal static string ExceptionLatLongIncorrect {
            get {
                return ResourceManager.GetString("ExceptionLatLongIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude and/or latitude outside valid bounds ([-179.9999,179.9999] for longitude, [-85.0511, 85.0511] for latitude)..
        /// </summary>
        internal static string ExceptionLatLongOutside {
            get {
                return ResourceManager.GetString("ExceptionLatLongOutside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading {0}. Image file corrupted ?.
        /// </summary>
        internal static string ExceptionLoadingImage {
            get {
                return ResourceManager.GetString("ExceptionLoadingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify at least one proxy list URL..
        /// </summary>
        internal static string ExceptionNoProxyList {
            get {
                return ResourceManager.GetString("ExceptionNoProxyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No proxy URL found in this page {0}..
        /// </summary>
        internal static string ExceptionNoProxyUrlFound {
            get {
                return ResourceManager.GetString("ExceptionNoProxyUrlFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while pasting image..
        /// </summary>
        internal static string ExceptionPastingImage {
            get {
                return ResourceManager.GetString("ExceptionPastingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy list exhausted, none working..
        /// </summary>
        internal static string ExceptionProxyListExhausted {
            get {
                return ResourceManager.GetString("ExceptionProxyListExhausted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG Image File (*.jpg;*.jpeg)|*.jpg;*.jpeg.
        /// </summary>
        internal static string JpegWildcard {
            get {
                return ResourceManager.GetString("JpegWildcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG Image Files (*.png)|*.png.
        /// </summary>
        internal static string PngWildcard {
            get {
                return ResourceManager.GetString("PngWildcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIFF Image Files (*.tif;*.tiff)|*.tif;*.tiff.
        /// </summary>
        internal static string TiffWildcard {
            get {
                return ResourceManager.GetString("TiffWildcard", resourceCulture);
            }
        }
    }
}
